services:
  postgres:
    container_name: pgvector_container
    image: myuser/pgvector
    environment:
      POSTGRES_USER: syash
      POSTGRES_PASSWORD: 2004
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: cahr2001@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 2004
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    network_mode: bridge
    ports:
      - "5050:80"
    restart: unless-stopped
    
volumes:
    postgres:
    pgadmin:
